language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run docs:build"

install: npm ci

script: npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist-gh-pages
  on:
    branch: master
